error CustomError {
  value: uint
}

fn throwCustomError(value: uint)
